name: anlamayanyok
description: Anlamayan yok description

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  http: ^0.13.1
  firebase_storage: ^8.0.3
  firebase_core: ^1.0.3
  firebase_analytics: ^7.1.1
  flutter_pdfview: ^1.1.0
  share: ^2.0.1
  cloud_firestore: ^1.0.5
  firebase_auth: ^1.1.0
  provider: ^5.0.0
  font_awesome_flutter: ^9.0.0
  flutter_signin_button: ^2.0.0
  image_picker: ^0.7.4
  permission_handler: ^7.0.0
  youtube_player_flutter: ^8.0.0
  path: ^1.8.0
  sqflite: ^2.0.0+3
  timeago: ^3.0.2
  flutter_spinkit: ^5.0.0
  flutter_email_sender: ^5.0.0
  material_floating_search_bar: ^0.3.4
  autocomplete_textfield: ^1.7.3
  dio: ^4.0.0
  flutter_native_splash: ^1.1.8+4
  in_app_purchase: ^1.0.0
  change_app_package_name: ^1.0.0
  url_launcher: ^6.0.4
  google_mobile_ads: ^0.13.0
  sizer: ^2.0.13
  flutter_slidable: ^0.6.0


dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "pdfs/app_icon.png"
  image_path_android: "pdfs/app_icon.png"

flutter_native_splash:
  color: "#f7fff9"
  image: pdfs/logomuz.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center


flutter:


  uses-material-design: true


  assets:
    - pdfs/icons/
    - veritabani/Ders_notlarim.sqlite
